# Generated by Django 3.0.7 on 2021-01-12 12:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_start_time', models.TimeField(verbose_name='start time')),
                ('gym_end_time', models.TimeField(verbose_name='end time')),
                ('max_number_of_users', models.IntegerField(validators=[django.core.validators.MaxValueValidator], verbose_name='max users')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_prevision', models.TimeField(verbose_name='end time')),
                ('date', models.DateField(verbose_name='date')),
                ('duration', models.TimeField(verbose_name='duration')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='price')),
                ('charge_paid', models.BooleanField(default=False, verbose_name='charge')),
                ('canceled', models.BooleanField(default=False, verbose_name='canceled')),
                ('refound', models.BooleanField(default=False, verbose_name='refound')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
