# Generated by Django 3.0.7 on 2021-01-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='duration'),
        ),
    ]
