# Generated by Django 3.0.7 on 2021-01-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210113_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='charge_paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
    ]
