# Generated by Django 3.0.7 on 2021-01-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210114_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='charge_id',
            field=models.CharField(default=10, max_length=25, verbose_name='charge'),
            preserve_default=False,
        ),
    ]
